# Generated by Django 3.0.6 on 2020-05-31 13:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0006_profileimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileimage',
            name='profile_image',
            field=models.ImageField(null=True, upload_to='profile'),
        ),
        migrations.AlterField(
            model_name='profileimage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
